export const APP_ACTIONS = {
  SELECT_TIMESTAMP: "SELECT_TIMESTAMP",
  LOAD_TIMESTAMPS: "LOAD_TIMESTAMPS",
  SORT_TIMESTAMPS: "SORT_TIMESTAMPS",

  SHOW_LOADER: "SHOW_LOADER",
  HIDE_LOADER: "HIDE_LOADER",
};
